#!/usr/bin/env bash
# Inventory package layer directories and write docs/generated/layer-inventory.md.
#
# Usage:
#   scripts/generate-layer-inventory.sh
#   scripts/generate-layer-inventory.sh --check
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

output_file="docs/generated/layer-inventory.md"
script_name="scripts/generate-layer-inventory.sh"
lint_contract="scripts/lint-layered-architecture.sh"
generated_at_policy="stable: no wall-clock timestamp; regenerate when packages/*/src/<layer>/ changes"

mode="write"
if [[ "${1:-}" == "--check" ]]; then
  mode="check"
elif [[ $# -gt 0 ]]; then
  printf 'usage: %s [--check]\n' "$script_name" >&2
  exit 2
fi

known_layers=(types config repo providers service runtime ui)

count_layer_files() {
  local layer_dir=$1
  find "$layer_dir" -type f \
    ! -path '*/node_modules/*' \
    ! -path '*/dist/*' \
    ! -path '*/build/*' \
    | wc -l | tr -d ' '
}

emit_inventory() {
  printf '<!-- generated by %s -->\n' "$script_name"
  printf '<!-- command: %s -->\n' "$script_name"
  printf '<!-- generated-at policy: %s -->\n' "$generated_at_policy"
  printf '<!-- do not edit below this line; re-run the script to refresh -->\n'
  printf '\n'
  printf '# Layer Inventory\n'
  printf '\n'
  printf 'Inventory of `packages/*/src/<layer>/` directories for the layered-domain contract.\n'
  printf '\n'
  printf '%s\n' "- Generator: \`$script_name\`"
  printf '%s\n' "- Check command: \`$script_name --check\`"
  printf '%s\n' "- Lint contract: \`$lint_contract\` and \`docs/references/layered-domain-architecture.md\`"
  printf '%s\n' "- Generated-at policy: \`$generated_at_policy\`"
  printf '\n'
  printf '| Package | Layer | Present | File count |\n'
  printf '%s\n' '| --- | --- | --- | ---: |'

  local found_package=0
  shopt -s nullglob
  for pkg_dir in packages/*; do
    [[ -d "$pkg_dir/src" ]] || continue
    found_package=1
    local package
    package=$(basename "$pkg_dir")
    local layer
    for layer in "${known_layers[@]}"; do
      local layer_dir="$pkg_dir/src/$layer"
      if [[ -d "$layer_dir" ]]; then
        printf '| `%s` | `%s` | yes | %s |\n' "$package" "$layer" "$(count_layer_files "$layer_dir")"
      else
        printf '| `%s` | `%s` | no | 0 |\n' "$package" "$layer"
      fi
    done
  done
  shopt -u nullglob

  if (( found_package == 0 )); then
    printf '| _(none)_ | _(none)_ | no | 0 |\n'
  fi
}

if [[ "$mode" == "check" ]]; then
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' EXIT
  emit_inventory > "$tmp"
  if [[ ! -f "$output_file" ]]; then
    printf '%s is missing; run %s\n' "$output_file" "$script_name" >&2
    exit 1
  fi
  if ! diff -u "$output_file" "$tmp"; then
    printf '%s is out of date; run %s\n' "$output_file" "$script_name" >&2
    exit 1
  fi
  printf 'layer inventory is current\n'
  exit 0
fi

emit_inventory > "$output_file"
printf 'wrote %s\n' "$output_file"
