#!/usr/bin/env bash
# Diff successive git log versions of docs/QUALITY_SCORE.md and emit one row
# per grade change into docs/generated/quality-score-history.md.
#
# Usage:
#   scripts/generate-quality-score-history.sh
#
# Run this script any time QUALITY_SCORE.md grades change (pre-commit hook,
# manual, or CI).  The output is committed alongside the source so agents
# always have a trend view without running git commands themselves.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

SOURCE_FILE="docs/QUALITY_SCORE.md"
OUTPUT_FILE="docs/generated/quality-score-history.md"
SCRIPT_NAME="scripts/generate-quality-score-history.sh"
RUN_TIMESTAMP="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Print "name|grade" pairs extracted from QUALITY_SCORE.md content on stdin.
# Matches pipe-delimited table rows where the second column is a single grade
# letter (A/B/C/D/F).  Skips separator and header rows.
extract_grades() {
  awk -F'|' '
    NF >= 4 {
      name  = $2
      grade = $3
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", name)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", grade)
      # Accept only valid single-letter grades; skip headers/separators
      if (grade ~ /^[ABCDF]$/ && name !~ /^-+$/ && name !~ /^(Grade|Layer|Gap|Domain)$/ && name != "") {
        print name "|" grade
      }
    }
  '
}

# Write grades for a specific commit to a temp file; return the path.
grades_for_commit() {
  local hash="$1"
  local tmp
  tmp="$(mktemp)"
  git show "${hash}:${SOURCE_FILE}" 2>/dev/null | extract_grades | sort > "$tmp"
  printf '%s' "$tmp"
}

# ---------------------------------------------------------------------------
# Walk git history oldest-first
# ---------------------------------------------------------------------------

mapfile -t commit_log < <(
  git log --follow --format="%H|%as" -- "$SOURCE_FILE" | tac
)

if (( ${#commit_log[@]} == 0 )); then
  printf 'no git history found for %s; nothing to generate\n' "$SOURCE_FILE" >&2
  exit 0
fi

declare -a rows=()   # "date|short_hash|name|from_grade|to_grade|note"
prev_tmp=""

for entry in "${commit_log[@]}"; do
  hash="${entry%%|*}"
  date="${entry##*|}"
  short="${hash:0:7}"

  cur_tmp="$(grades_for_commit "$hash")"

  if [[ -z "$prev_tmp" ]]; then
    # First commit — record every grade as its initial value
    while IFS='|' read -r name grade; do
      [[ -n "$name" ]] && rows+=("${date}|${short}|${name}|—|${grade}|initial")
    done < "$cur_tmp"
  else
    # New rows or changed grades relative to the previous commit
    while IFS='|' read -r name grade; do
      [[ -z "$name" ]] && continue
      prev_grade="$(awk -F'|' -v n="$name" '$1 == n {print $2}' "$prev_tmp")"
      if [[ -z "$prev_grade" ]]; then
        rows+=("${date}|${short}|${name}|—|${grade}|added")
      elif [[ "$prev_grade" != "$grade" ]]; then
        rows+=("${date}|${short}|${name}|${prev_grade}|${grade}|grade change")
      fi
    done < "$cur_tmp"
    # Detect removals
    while IFS='|' read -r name grade; do
      [[ -z "$name" ]] && continue
      if ! grep -q "^${name}|" "$cur_tmp" 2>/dev/null; then
        rows+=("${date}|${short}|${name}|${grade}|—|removed")
      fi
    done < "$prev_tmp"
    rm -f "$prev_tmp"
  fi

  prev_tmp="$cur_tmp"
done
[[ -n "$prev_tmp" ]] && rm -f "$prev_tmp"

# ---------------------------------------------------------------------------
# Write output
# ---------------------------------------------------------------------------

{
  printf '<!-- generated by %s -->\n' "$SCRIPT_NAME"
  printf '<!-- command: %s -->\n' "$SCRIPT_NAME"
  printf '<!-- last run: %s -->\n' "$RUN_TIMESTAMP"
  printf '<!-- do not edit by hand; re-run the script to refresh -->\n'
  printf '\n'
  printf '# Quality-Score History\n'
  printf '\n'
  printf 'Grade changes extracted from `git log -- %s`.\n' "$SOURCE_FILE"
  printf 'Current snapshot: [docs/QUALITY_SCORE.md](../QUALITY_SCORE.md)\n'
  printf '\n'
  printf 'Generated: `%s`  \n' "$RUN_TIMESTAMP"
  printf 'Source script: `%s`  \n' "$SCRIPT_NAME"
  printf '\n'

  if (( ${#rows[@]} == 0 )); then
    printf 'No grade changes detected across %d commit(s).\n' "${#commit_log[@]}"
  else
    printf '| Date | Commit | Domain / Layer | From | To | Note |\n'
    printf '| --- | --- | --- | --- | --- | --- |\n'
    for row in "${rows[@]}"; do
      IFS='|' read -r r_date r_short r_name r_from r_to r_note <<< "$row"
      printf '| %s | %s | %s | %s | %s | %s |\n' \
        "$r_date" "$r_short" "$r_name" "$r_from" "$r_to" "$r_note"
    done
  fi
} > "$OUTPUT_FILE"

printf 'wrote %s (%d row(s) across %d commit(s))\n' \
  "$OUTPUT_FILE" "${#rows[@]}" "${#commit_log[@]}"
